<template>
  <div><div class="page-head"><div><h1>Academic programs</h1><p>Manage the catalog, poster images, visibility, and recommendation profiles.</p></div><button v-if="auth.canManageStudents" class="primary" @click="edit()">Add program</button></div><div v-if="error" class="error">{{ error }}</div>
    <section class="program-grid"><article v-for="c in courses" :key="c.id" class="panel program"><img v-if="c.image_path" :src="imageUrl(c.image_path)" :alt="`${c.code} poster`"><div class="program-body"><span>{{ c.code }} · {{ c.program_type }}</span><h2>{{ c.name }}</h2><p>{{ c.institute }}</p><small>{{ c.duration }} · {{ c.recommendations_count }} recommendations · {{ c.is_active ? 'Published' : 'Hidden' }}</small><div v-if="auth.canManageStudents"><button class="secondary" @click="edit(c)">Edit</button><button class="danger" @click="remove(c)">Delete</button></div></div></article></section>
    <div v-if="form" class="modal-wrap" @click.self="form=null"><form class="modal" @submit.prevent="save"><h2>{{ form.id?'Edit':'Add' }} program</h2><div class="form-grid"><div class="field"><label>Code</label><input v-model="form.code" required></div><div class="field"><label>Duration</label><input v-model="form.duration" required></div><div class="field full"><label>Name</label><input v-model="form.name" required></div><div class="field full"><label>Institute</label><input v-model="form.institute"></div><div class="field full"><label>Description</label><textarea v-model="form.description" required></textarea></div><div class="field"><label>Program type</label><select v-model="form.program_type"><option value="degree">Degree</option><option value="certificate">Certificate</option></select></div><div class="field"><label>Display order</label><input v-model.number="form.display_order" type="number" min="0"></div><div class="field full"><label>Subjects (one per line)</label><textarea v-model="form.subjectsText"></textarea></div><div class="field full"><label>Career paths (one per line)</label><textarea v-model="form.careersText"></textarea></div><div class="field full"><label>Poster image (max 8 MB)</label><input type="file" accept="image/*" @change="pickImage"></div><label class="check"><input v-model="form.is_active" type="checkbox"> Published</label><label class="check"><input v-model="form.is_recommendable" type="checkbox"> Include in recommendations</label></div><div class="modal-actions"><button type="button" class="secondary" @click="form=null">Cancel</button><button class="primary">Save program</button></div></form></div>
  </div>
</template>
<script setup>
import{onMounted,ref}from'vue';import api,{errorMessage}from'../utils/api';import{useAdminAuth}from'../stores/auth';const auth=useAdminAuth(),courses=ref([]),form=ref(null),error=ref('');const base=(import.meta.env.VITE_API_URL||'http://localhost:8000/api').replace(/\/api$/,'');const imageUrl=path=>`${base}/api/storage/${path}`;const load=async()=>{courses.value=(await api.get('/admin/courses')).data.courses};const edit=c=>form.value=c?{...c,subjectsText:(c.subjects||[]).join('\n'),careersText:(c.career_paths||[]).join('\n'),image:null}:{code:'',name:'',institute:'',description:'',duration:'4 years',program_type:'degree',display_order:courses.value.length+1,is_active:true,is_recommendable:true,subjectsText:'',careersText:'',image:null};const pickImage=e=>{form.value.image=e.target.files[0]||null};const lines=value=>value.split('\n').map(v=>v.trim()).filter(Boolean);const save=async()=>{try{error.value='';const data=new FormData();const payload={...form.value};const ignored=['subjectsText','careersText','subjects','career_paths','recommendation_profile','id','image_path','recommendations_count','created_at','updated_at','image'];Object.entries(payload).forEach(([key,value])=>{if(ignored.includes(key)||value===null)return;if(typeof value==='boolean')data.append(key,value?'1':'0');else data.append(key,value)});lines(form.value.subjectsText).forEach((value,index)=>data.append(`subjects[${index}]`,value));lines(form.value.careersText).forEach((value,index)=>data.append(`career_paths[${index}]`,value));if(form.value.image)data.set('image',form.value.image);if(form.value.id){data.append('_method','PUT');await api.post(`/admin/courses/${form.value.id}`,data)}else await api.post('/admin/courses',data);form.value=null;await load()}catch(e){error.value=errorMessage(e)}};const remove=async c=>{if(!confirm(`Delete ${c.code}?`))return;try{await api.delete(`/admin/courses/${c.id}`);await load()}catch(e){error.value=errorMessage(e)}};onMounted(load);
</script>
<style scoped>.program-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.program{overflow:hidden;border-top:4px solid #e5bd2e}.program img{width:100%;aspect-ratio:1;object-fit:cover;background:#edf2ed}.program-body{padding:20px}.program-body>span{font-size:10px;font-weight:900;color:#177044;text-transform:uppercase}.program h2{font:21px Georgia;color:#143f28}.program p{color:#68756d;font-size:12px}.program small{display:block;color:#8a948d;margin:17px 0}.program-body div{display:flex;gap:8px}.check{display:flex;align-items:center;gap:8px;font-size:13px}@media(max-width:900px){.program-grid{grid-template-columns:1fr}}</style>
